# 1\. 인덱싱 indexing
- 인덱싱은 특정 값을 지정할때 사용한다.
- 파이선 리스트와 동일한 개념으로 사용한다.
- 원소 여러개를 사용할 경우 ,(콤마)를 이용해 각 차원의 인덱스에 접근한다.
- 인덱싱 할 때 마다 차원이 감소한다.


## 1차원 배열 인덱싱

In [1]:
import numpy as np
x = np.arange(10)

In [2]:
x[0]

np.int64(0)

In [3]:
x[9], x[-1]

(np.int64(9), np.int64(9))

In [4]:
x[3] = 100
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

- x는 1차원 배열
- x[0]은 0차원이 된다.
- index의 결과값은 차원이 감소된 결과값이 출력된다.

## 2차원 행렬 인덱싱

In [5]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x.shape

(2, 5)

In [7]:
x.ndim

2

In [8]:
x[0]

array([0, 1, 2, 3, 4])

In [9]:
x[1]

array([5, 6, 7, 8, 9])

In [10]:
x[0][2]

np.int64(2)

In [11]:
x[0,2]

np.int64(2)

In [12]:
x[1,2]

np.int64(7)

In [13]:
x[1,4], x[1,-1], x[-1, -1]

(np.int64(9), np.int64(9), np.int64(9))

## 3차원 인덱싱

In [14]:
x = np.arange(36).reshape(3,4,3)

In [15]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
x[1]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
x[2]

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [18]:
x[0,1]

array([3, 4, 5])

In [21]:
x[0, 1, 2], x[0][1][2]

(np.int64(5), np.int64(5))

# 2\. 슬라이싱
- 슬라이싱은 데이터의 범위를 지정할 때 사용한다.
- 리스트, 문자열 slicing 과 동일한 개념으로 사용한다.
- 각 열과 행 구분은 , 로 하며 각 차원별로 슬라이싱이 가능하다.
- 슬라이싱은 차원의 변화가 없다.

## 1차원 슬라이싱

In [22]:
x = np.arange(10)

In [23]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [24]:
x[1::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[::2]

array([0, 2, 4, 6, 8])

In [29]:
x[1::3]

array([1, 4, 7])

In [30]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2차원 슬라이싱

In [31]:
x = np.arange(15).reshape(3,5)

In [32]:
x[0]

array([0, 1, 2, 3, 4])

In [33]:
x[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
x[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
x[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [37]:
x[0:2, 0:2]

array([[0, 1],
       [5, 6]])

## 문제.   
위 2차원 배열에서 [[0,1].[5,6]] 만 가져오기



In [38]:
x[:2, :2]

array([[0, 1],
       [5, 6]])

## 3차원 슬라이싱

In [39]:
x = np.arange(54).reshape(2,9,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [ ]:
x[:1][:2] # 3차원에서는 다른 값이 나올 수 있다.

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
x[0][:2][:]

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
x[:1, :2]

array([[[0, 1, 2],
        [3, 4, 5]]])

## 문제    
위 내용에서 [[4,5], [31,32]] 를 출력해 보세요.

In [51]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [50]:
x[:,1,1:]

array([[ 4,  5],
       [31, 32]])

## 문제    
다음 결과를 만들어 보세요.
```
[[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
 [27, 30, 33, 36, 39, 42, 45, 48, 51]]
```

In [54]:
x[:, :, 0]

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
       [27, 30, 33, 36, 39, 42, 45, 48, 51]])

## ndarray 는 iterable 하다

In [55]:
arr = np.arange(1 , 6)
arr

array([1, 2, 3, 4, 5])

In [56]:
for i in arr:
    print(i)

1
2
3
4
5


In [57]:
arr = np.arange(10, 70, 10).reshape(2,3)
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [58]:
for i in arr:
    print(i)

[10 20 30]
[40 50 60]


앞으로 데이터분석이나, 인공지능에서 다루게 될
수많은 데이터 들이 적게는 3, 4차원에서 많게는 수십 수백차원 데이터도 다룰수 있다. 사실상 3차원 이상의 데이터는 시각화가 거의 불가능 합니다. 머리속으로 차근차근 생각하면서 차원 다루기에 익숙해져야 합니다.