# Broadcasting

#### 브로드캐스팅
  - (기본적으로)Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - **다른 Shape을 갖는 array 간 연산** 의 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

#### 브로드캐스팅 Rule
 - [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1인 것이 존재**하면 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장(stretch)** 된다

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

- Broadcatding 의 강점은 shape 가 다른 데이터 까지의 연산을 '특별한 처리' 없이도 연산이 가능케 한다.

## Shape 이 같은 연산

In [1]:
import numpy as np 
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
y = np.random.rand(15).reshape(3,5)
y

array([[0.44379179, 0.66071362, 0.61023282, 0.6523957 , 0.697815  ],
       [0.79433147, 0.81917616, 0.45983534, 0.39671678, 0.32362754],
       [0.23941312, 0.19301059, 0.61238589, 0.27533212, 0.70487523]])

In [4]:
x + y

array([[ 0.44379179,  1.66071362,  2.61023282,  3.6523957 ,  4.697815  ],
       [ 5.79433147,  6.81917616,  7.45983534,  8.39671678,  9.32362754],
       [10.23941312, 11.19301059, 12.61238589, 13.27533212, 14.70487523]])

## Shape이 다른 경우 연산

In [5]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)

In [6]:
a, b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([100, 101, 102]))

In [7]:
a.shape, b.shape

((4, 3), (3,))

In [8]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [9]:
c = np.arange(1000, 1004)
c

array([1000, 1001, 1002, 1003])

- 행렬의 수가 다르면 에러가 발생한다.

In [10]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [11]:
d = b.reshape(1,3)
d

array([[100, 101, 102]])

In [12]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [14]:
d = np.arange(6)
d

array([0, 1, 2, 3, 4, 5])

In [15]:
a + d

ValueError: operands could not be broadcast together with shapes (4,3) (6,) 

In [17]:
d = d.reshape(2,3)
d

array([[0, 1, 2],
       [3, 4, 5]])

- 열이 같다고 하더라도 행의 수가 하나이거나 같아야 한다.

In [19]:
a + d

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

In [20]:
a.shape

(4, 3)

In [21]:
x = np.array([[[[10]]]])
x

array([[[[10]]]])

In [22]:
x.shape

(1, 1, 1, 1)

In [23]:
a + x

array([[[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18],
         [19, 20, 21]]]])

## 문제.   
위 두개의 array를 더하여 아래와 같은 결과를 만들어 보세요.
```
array([[11,22,31], [42,51,62]])
```

In [24]:
arr21 = np.arange(10,70,10).reshape(2,3)
arr21

array([[10, 20, 30],
       [40, 50, 60]])

In [26]:
arr23 = np.array([1,2])
arr23

array([1, 2])

In [30]:
(arr21.T + arr23).T

array([[11, 21, 31],
       [42, 52, 62]])

In [31]:
arr21.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [32]:
arr21.reshape(3,2) + arr23

array([[11, 22],
       [31, 42],
       [51, 62]])

In [33]:
(arr21.reshape(3,2) + arr23).reshape(2,3)

array([[11, 22, 31],
       [42, 51, 62]])

## Broadcasting Rule
- [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1인 것이 존재**하면 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장(stretch)** 된다

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

```
    브로드캐스팅 가용한 경우
    
    A     : 256 x 256 x 3
    B     :             3
    Result: 256 x 256 x 3   <-- 결과 차원은 둘중 큰 size의 차원으로 확장

    A     : 8 x 1 x 6 x 1
    B     :     7 x 1 x 5
    Result: 8 x 7 x 6 x 5       
```

In [34]:
a = np.full(4, 100)
a

array([100, 100, 100, 100])

In [35]:
a + 1

array([101, 101, 101, 101])

In [36]:
a + [1]

array([101, 101, 101, 101])

In [37]:
a + [[1]]

array([[101, 101, 101, 101]])

In [38]:
a + [1,2,3,4]

array([101, 102, 103, 104])

In [39]:
a + [1, 2]

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [40]:
b = np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
a + b

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [42]:
b = np.arange(1,3).reshape(2,1)
b

array([[1],
       [2]])

In [43]:
a + b

array([[101, 101, 101, 101],
       [102, 102, 102, 102]])

In [44]:
b = np.arange(6).reshape(2,3,1)
b

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [45]:
a + b

array([[[100, 100, 100, 100],
        [101, 101, 101, 101],
        [102, 102, 102, 102]],

       [[103, 103, 103, 103],
        [104, 104, 104, 104],
        [105, 105, 105, 105]]])